const DATA = [
  {
    id: 1,
    name: 'Agentic structures using classical solvers',
    link:
      'https://agenttoolkit.github.io/agent-lifecycle-toolkit/concepts/components/refraction/',
    image: 'refraction',
    patch: true,
    primary: true,
    secondary: false,
    tertiary: false,
    tags: [],
  },
  {
    id: 11,
    name: 'ALTK',
    link: 'https://github.com/AgentToolkit/agent-lifecycle-toolkit',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 12,
    name: 'Refraction',
    link:
      'https://agenttoolkit.github.io/agent-lifecycle-toolkit/concepts/components/refraction/',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 3,
    name: 'Process Automation',
    link: null,
    image: 'process',
    primary: false,
    secondary: true,
    tertiary: false,
    tags: ['bpm'],
  },
  {
    id: 2,
    name: 'Human-Aware Planning and Explainable AI',
    link: null,
    image: 'xai',
    primary: true,
    secondary: false,
    tertiary: false,
    tags: ['xai', 'humanai'],
  },
  {
    id: 4,
    name: 'Mixed Reality',
    link: null,
    image: 'vamhri',
    primary: false,
    secondary: true,
    tertiary: false,
    tags: ['vamhri'],
  },
  {
    id: 5,
    name: 'AI4BPM @ AAAI',
    link: 'https://ai4bpm.com',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 6,
    name: 'XAIP @ ICAPS',
    link: 'https://explainableplanning.com',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 7,
    name: 'VAM-HRI @ HRI',
    link: 'http://vamhri.com',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 8,
    name: 'Watson Orchestrate',
    link: 'https://www.ibm.com/products/watsonx-orchestrate',
    image: 'wo',
    primary: false,
    secondary: false,
    tertiary: true,
  },
];

export default DATA;
